(define (hanoi n from to aux)
  (when (> n 0)
    (hanoi (- n 1) from aux to)
    (display "Переместить диск ")
    (display n)
    (display " с ")
    (display from)
    (display " на ")
    (display to)
    (newline)
    (hanoi (- n 1) aux to from)))

(define (main)
  (display "=== Ханойские башни ===")
  (newline)
  (display "Количество дисков: 6")
  (newline)
  (hanoi 2 'A 'C 'B))

(main)